### ISSUE TITLE
Error in creating dummy VA events

### ISSUE THREAD

**Issue by harleen0202** [SwissTPH/dhis2_va_draft#48]
While creating the dummy VA events as mentioned in DHIS2_VA_program/docs/2.30-Tracker/Demo-Setup.md,  I am getting this error:

Traceback (most recent call last):
  File "post_demo_events.py", line 271, in <module>
    va_programs = api.get('programs', params={'filter': 'name:like:Verbal Autopsy'}).get('programs')
  File "post_demo_events.py", line 58, in get
    except requests.RequestException as e:
NameError: global name 'requests' is not defined

Please check

**Comment by gocastro** [comment]
it seems like you did not install the python 'requests' library
